### ISSUE TITLE
Missing Namespace

### ISSUE THREAD

**Issue by simPod** [bpolaszek/php-iterable-functions#1]
Hey! These functions look very neat, I was just wondering whether there shouldn't be any namespace declared for this lib to avoid eventual conflicts. Thanks!

**Comment by simPod** [comment]
Abandoned repo, closing.

**Comment by bpolaszek** [comment]
Hey, sorry, completely miss the notice of an issue here. 

I didn't namespace it because it was designed for a [is_iterable](https://www.php.net/manual/fr/function.is-iterable.php) polyfill - if native function exist, it takes precedence.

Thank you,
Ben
