### ISSUE TITLE
iterable_values

### ISSUE THREAD

**Issue by JoshuaBehrens** [bpolaszek/php-iterable-functions#38]
Do you have thoughts on iterable_values? I am missing that key-resetting partner-in-crime to array_values.

**Comment by bpolaszek** [comment]
Hello there,

It's on its way: https://github.com/bpolaszek/php-iterable-functions/pull/33 🚀 

Planned for 2.0, to be released soon. You can already `composer req bentools/iterable-functions:^2.0@beta` to get it earlier.

**Comment by JoshuaBehrens** [comment]
Woop woop 🎉
