### ISSUE TITLE
Drop EOLed PHP support

### ISSUE THREAD

**Issue by simPod** [bpolaszek/php-iterable-functions#8]
Hi, I'd like to refactor this a bit while dropping old PHP support (keeping 7.2+), bumping versions and adding type hints and templated annotations for psalm.

Let me know if interested. I'd do it in small PRs.

**Comment by bpolaszek** [comment]
Hey @simPod, I think it would be a good idea, like keeping the old 1.x branch for 5.3+ compatibility and introduce a 2.x version compatible for PHP7+, now that PHP7 has been widely adopted.
I'm 👍 for this!

**Comment by simPod** [comment]
Should I go against master then?

**Comment by bpolaszek** [comment]
`2.0.x-dev` for those PRs 🙂
